---
global:
  file_types: [".mp4", ".mkv"]

plex:
  url: https://plex.example.com:32400
  token: CHANGEME
  library: "PreRoll"

default:
  search_string: default
  mode: random

schedule:
  - name: Halloween
    search_string: halloween
    mode: random
    month: oct,nov
    days: "*"

  - name: Christmas
    search_string: christmas
    mode: random
    month: dec
    days: "*"

  - name: New Years
    search_string: new_years
    mode: random
    month: jan
    days: [1, 2, 3, 4, 5, 6]
