name: Build and publish Docker image

on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  IMAGE_TAG: "ghcr.io/${{ github.actor }}/${{ github.event.repository.name }}:0.2.1"

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - run: echo "$GITHUB_CONTEXT"

      - run: echo "${{ github }}"

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Github Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image and push to GitHub Container Registry
        uses: docker/build-push-action@v3
        with:
          context: .
          build-args: |
            TITLE=Auto Pre-roll
            VCS_URL=${{ github.actor }}
          tags: |
            ${{ env.IMAGE_TAG }}
            "ghcr.io/${{ github.actor }}/${{ github.event.repository.name }}:latest"
          # build on feature branches, push only on main branch
          push: ${{ github.ref == 'refs/heads/main' }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
