name: Build and publish Docker image

on:
  push:
    branches:
      - main

env:
  REGISTRY_USERNAME: ${{ github.actor }}
  REGISTRY_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  REGISTRY_URL: ghcr.io/${{ github.actor }}
  REPO_NAME: ${{ github.event.repository.name }}
  IMAGE_TAG: "$REGISTRY_URL/$REPO_NAME:latest"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v2
      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v2
      - name: Build Docker image
        run: docker build -t "${ IMAGE_TAG }" .

  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Github Container Registry
        run: echo "${ REGISTRY_TOKEN }" | docker login ghcr.io -u "${ REGISTRY_USERNAME }" --password-stdin
      - name: Publish to Github Container Registry
        run: docker push "${ IMAGE_TAG }"
